### ISSUE TITLE
First contract is too hard?

### ISSUE THREAD

**Issue by dbeckwith** [SpaceTradersAPI/api-docs#30]
This is more of a game balance question, sorry if this isn't the right place for those.

My very first contract that I got when creating my first account seems to require a whopping 13,700 aluminum ore, and I was only given three days to complete it. Since it's my first time playing I've already spent a couple days just getting my script going, and have just now gotten a basic mining loop working with about a day remaining. The basic mining ship I bought only has a cargo space of 30 and extracts like 10 ore at a time.

Is there a bug with the contract terms? It seems like this is way too much to deliver for the very first contract.

**Comment by TylerD94** [comment]
Mine was also pretty high (10k?) I think I have another 4 days to do it, but I agree, it does seem quite high for starting out. Maybe need to buy a few more ships to complete it. Best of luck!

**Comment by space-admiral** [comment]
Oh ya that seems way too high for only a few days. We'll lower the units and extend the expiration quite a bit. Thanks for bringing this up!

**Comment by javierjulio** [comment]
Oof and I was coming here to say that 1200 units was too high. Just started today and the starter contract was for 1,220 units of platinum ore. With my ship (60 capacity) and mining drone (30 capacity), it would take well over 10 trips to fulfill. This was for the Quickstart so I think it would help to really lower that to finish that loop. Otherwise its a lot of repeat steps and waiting to complete the Last Steps section of the Quickstart.

**Comment by space-admiral** [comment]
The first contract should be quite a bit easier and provide some more credits. Thanks for reporting this!
