### ISSUE TITLE
The Dock & Orbit endpoints differ in response format

### ISSUE THREAD

**Issue by wolfadex** [SpaceTradersAPI/api-docs#34]
Not sure if this applies to other endpoints as well but noticing it with docking and orbiting.

When I request `/my/agent` I get back `{ data: { /* agent details */ } }`, when I request `/my/ships` I get back `{ data: [ /* ships */ ] }`, and so on. However when I request `/my/ships/<id>/dock` I get back `{ data: { nav: { /* nav details */ } }` and same for `/my/ships/<id>/dock`. I think it'd be more consistent to return `{ data: { /* nav details */ } }`.

**Comment by space-admiral** [comment]
Thanks for reporting this! I think I remember the intention here - in a GET request we return directly the object being fetched in the data key (or array of objects) but for POST requests we try to return all of the objects that were mutated as a result of that action. For example, a purchase request will return your agent + ship cargo since credits and cargo changed.

So for a rule of thumb, POST requests will contain a key of each object that changed, and in this case its only the nav that was altered (later you might also take some damage to your ship docking on a planet).

Let me know if that helps at all, or if you think even with that info its still confusing / annoying, and we can think more about it.
